name: ABC Alerts

on:
  schedule:
    # Ejecuta todos los días a las 9:00 UTC
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  run-alerts:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar código
        uses: actions/checkout@v4


      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Ejecutar ABC Alerts
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}

        run: |
          python main.py
